name: Publish release to Nexus

on:
  workflow_run:
    workflows: [ Create release and iterate versions ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'

      - name: Create settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: |
            [{
              "id": "nexus-kaurpalang-releases",
              "username": "${{secrets.NEXUS_USERNAME}}",
              "password": "${{secrets.NEXUS_PASSWORD}}"
            }]

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to Nexus
        run: mvn deploy -DskipTests