name: Publish release to Nexus
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Clean settings.xml
        run: rm -rf ~/.m2/settings.xml

      - name: Create settings.xml
        uses: s4u/maven-settings-action@v1
        with:
          servers: '[{"id": "nexus-kaurpalang-releases", "username": "github", "password": "${{secrets.NEXUS_PASSWORD}}"}]'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to Nexus
        run: mvn deploy -DskipTests
