name: Publish plugin snapshot to Nexus
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://nexus.kaurpalang.com/
        username: github
        p: ${{ secrets.GITHUBNEXUSPASSWORD }}
        format: maven2
        repository: personal-snapshots
        coordinates: groupId=net.kaurpalang artifactId=mirth-plugin-maven-plugin version=0.1-SNAPSHOT
        assets: extension=jar
        filename: ./target/mirth-plugin-maven-plugin-1.0-SNAPSHOT.jar
